/* project/i18n/en-US/radius.js */
(function (root) {
  'use strict';
  root.__AW_I18N__.register('en-US', 'radius', {
    "t001": "Foundations · Radius and Shadow",
    "t002": "Radius and Elevation",
    "t003": "Single 6px rounded corners as system default. Three levels of projection; exercise restraint - the interface should be flat, bearing only visible height differences on the floating layer.",
    "t004": "Rounded corners",
    "t005": "Shadow · 4 layers + 4 directions",
    "t006": "Shading expresses \"height difference\". Layer 0 = flat (1px border only); Layer 1-3 = getting closer to the user. The direction follows the light source, with fixed panels casting shadows in the opposite direction. All tokens are generated by superimposing two layers of shadows (near + far), which is softer.",
    "t007": "Directional variant · Directional Shadow",
    "t008": "Defaults to all shadows pointing downward (light source on top). Fixed panels need to be back-projected by orientation - a sense of border floating above the content.",
    "t009": "upward",
    "t010": "Bottom toolbar / paging",
    "t011": "Down · Default",
    "t012": "Top navbar / card",
    "t013": "Right",
    "t014": "Left sidebar / drawer",
    "t015": "Left",
    "t016": "Right sidebar / drawer / fixed column",
    "t017": "Dark mode:",
    "t018": "Pure black + alpha mentioned 0.4-0.6. The third gear synchronization covers the",
    "t019": "of",
    "t020": "Under selector."
  });
})(typeof window !== 'undefined' ? window : globalThis);
